version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  initial-indexing:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: initial-indexing
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../scripts:/app/scripts
      - ../config.yaml:/app/config.yaml
    working_dir: /app
    command: python scripts/initial_indexing.py
    depends_on:
      - mongodb
    networks:
      - default

  query-processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: query-processor
    stdin_open: true
    tty: true
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../config.yaml:/app/config.yaml
    working_dir: /app
    command: python src/query_processor/query_processor.py

volumes:
  mongodb_data:
